from typing import List, Dict, TypedDict, Any, Optional

class CoreBianState(TypedDict):
    """
    The shared state for the Bian agent workflow.
    It holds all the data as it's processed by the different modules.
    """
    # --- Inputs ---
    requirements_folder: str
    endpoint_json_path: str
    project_structure_path: Optional[str] # Optional folder tree input
    bian_dir: Optional[str] 
    endpoints_dir: Optional[str] 

    # --- Module Outputs & Intermediate Data ---
    # Raw content loaded by the first module
    raw_requirements_content: List[str]
    endpoint_data: Dict[str, Any]
    initial_project_structure: Dict[str, Any]

    # Data extracted by the analysis module
    target_language: str
    target_framework: str
    target_architecture: str

    # Structure generated by the structure module
    proposed_project_structure: Dict[str, Any] # e.g., {'structure_tree': '...', 'file_details': {...}}

    # --- Final Output ---
    generated_requirements: str # Tentative final requirements
    updated_requirements: str # The final synthesized markdown

    # --- System State ---
    errors: List[str]
    module_results: Dict[str, Any]